### ISSUE TITLE
Centroid File

### ISSUE THREAD

**Issue by Bananamannn** [cherryphilip74/BrewPiLess-All-InOne#2]
Really like this All-in-one board. I have a copy of the BOM file but I was wondering if you would be able to supply a parts placement .csv file?

Or alternatively if you could send me the KiCad / Eagle files as I don't have the tools to mount SMD parts at home.
[BOM_PHI_BrewPiLess.xlsx](https://github.com/cherryphilip74/BrewPiLess-All-InOne/files/6620136/BOM_PHI_BrewPiLess.xlsx)

**Comment by cherryphilip74** [comment]
Answered by email.

 

CherryPhilip

 

From: Bananaman ***@***.***> 
Sent: mercoledì 9 giugno 2021 01:32
To: cherryphilip74/BrewPiLess-All-InOne ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cherryphilip74/BrewPiLess-All-InOne] Centroid File (#2)

 

Really like this All-in-one board. I have a copy of the BOM file but I was wondering if you would be able to supply a parts placement .csv file?

Or alternatively if you could send me the KiCad / Eagle files as I don't have the tools to mount SMD parts at home.
BOM_PHI_BrewPiLess.xlsx <https://github.com/cherryphilip74/BrewPiLess-All-InOne/files/6620136/BOM_PHI_BrewPiLess.xlsx>
